### ISSUE TITLE
KMD rewards

### ISSUE THREAD

**Issue by jr-ici** [pbca26/hw-kmd-reward-claim#19]
Hi,

I used twice (24 Jul 2021, and 25 Aug 2021) the KMD claiming tool (https://pbca26.github.io/hw-kmd-wallet/) and the rewards, instead of adding to my Ledger Nano X KMD balance, they were subtracted (from my balance).

Do you please know some way to rectify these two transactions?

Many thanks!
JR

**Comment by pbca26** [comment]
Please use https://github.com/pbca26/hw-kmd-wallet/issues next time.
